In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [ ]:
# CONTENT BASED FILTERING

In [ ]:
# Load the dataset
moviess =pd.read_csv('../data/TMDB_movie_dataset_v11.csv')

In [30]:
moviess.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [31]:
moviess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226610 entries, 0 to 1226609
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1226610 non-null  int64
 1   title                 1226597 non-null  object
 2   vote_average          1226610 non-null  float64
 3   vote_count            1226610 non-null  int64
 4   status                1226610 non-null  object
 5   release_date          1000315 non-null  object
 6   revenue               1226610 non-null  int64
 7   runtime               1226610 non-null  int64
 8   adult                 1226610 non-null  bool
 9   backdrop_path         318326 non-null   object
 10  budget                1226610 non-null  int64
 11  homepage              128595 non-null   object
 12  imdb_id               623496 non-null   object
 13  original_language     1226610 non-null  object
 14  original_title        1226597 non-null  object
 15  overview              966169 non-null   object
 16  popularity            1226610 non-null  float64
 17  poster_path           822380 non-null   object
 18  tagline               172119 non-null   object
 19  genres                717394 non-null   object
 20  production_companies  542668 non-null   object
 21  production_countries  664094 non-null   object
 22  spoken_languages      685852 non-null   object
 23  keywords              321108 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 216.4+ MB

In [32]:
moviess.shape

(1226610, 24)

In [33]:
for col in moviess.columns:
    print(f"{col}:{type(moviess[col])}")

id:<class 'pandas.core.series.Series'>
title:<class 'pandas.core.series.Series'>
vote_average:<class 'pandas.core.series.Series'>
vote_count:<class 'pandas.core.series.Series'>
status:<class 'pandas.core.series.Series'>
release_date:<class 'pandas.core.series.Series'>
revenue:<class 'pandas.core.series.Series'>
runtime:<class 'pandas.core.series.Series'>
adult:<class 'pandas.core.series.Series'>
backdrop_path:<class 'pandas.core.series.Series'>
budget:<class 'pandas.core.series.Series'>
homepage:<class 'pandas.core.series.Series'>
imdb_id:<class 'pandas.core.series.Series'>
original_language:<class 'pandas.core.series.Series'>
original_title:<class 'pandas.core.series.Series'>
overview:<class 'pandas.core.series.Series'>
popularity:<class 'pandas.core.series.Series'>
poster_path:<class 'pandas.core.series.Series'>
tagline:<class 'pandas.core.series.Series'>
genres:<class 'pandas.core.series.Series'>
production_companies:<class 'pandas.core.series.Series'>
production_countries:<class 'pandas.core.series.Series'>
spoken_languages:<class 'pandas.core.series.Series'>
keywords:<class 'pandas.core.series.Series'>

In [34]:
# Select relevant features
moviess = moviess[['title', 'overview', 'tagline', 'genres', 'keywords','production_companies', 'spoken_languages', 'original_language']]

In [35]:
moviess.head()

,title,overview,tagline,genres,keywords,production_companies,spoken_languages,original_language
0,Inception,"Cobb, a skilled thief who commits corporate es...",Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","Legendary Pictures, Syncopy, Warner Bros. Pict...","English, French, Japanese, Swahili",en
1,Interstellar,The adventures of a group of explorers who mak...,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","Legendary Pictures, Syncopy, Lynda Obst Produc...",English,en
2,The Dark Knight,Batman raises the stakes in his war on crime. ...,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","DC Comics, Legendary Pictures, Syncopy, Isobel...","English, Mandarin",en
3,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","Dune Entertainment, Lightstorm Entertainment, ...","English, Spanish",en
4,The Avengers,When an unexpected enemy emerges and threatens...,Some assembly required.,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Marvel Studios,"English, Hindi, Russian",en

### Fill missing values with empty string

In [36]:
for col in ['title', 'overview', 'tagline', 'genres', 'keywords', 'production_companies', 'spoken_languages', 'original_language']:
    moviess[col] = moviess[col].fillna('')

### Split comma-separated strings into lists

In [37]:
columns_to_split = ['genres', 'keywords', 'production_companies', 'spoken_languages']

for col in columns_to_split:
    moviess[col] = moviess[col].apply(lambda x: x.split(',') if x != '' else [])

#### Combine the relevant textual information from different columns into one column called "tags"

In [38]:
def collapse(elements):
    return ' '.join(elements)

moviess['tags'] = (moviess['title']+ ' ' +
                   moviess['overview'] + ' ' +
                   moviess['tagline'] + ' ' +
                   moviess['genres'].apply(collapse) + ' ' +
                   moviess['keywords'].apply(collapse) + ' ' +
                   moviess['production_companies'].apply(collapse) + ' ' +
                   moviess['spoken_languages'].apply(collapse) + ' ' +
                   moviess['original_language']
                   )

In [39]:
#Preview
moviess.head()

,title,overview,tagline,genres,keywords,production_companies,spoken_languages,original_language,tags
0,Inception,"Cobb, a skilled thief who commits corporate es...",Your mind is the scene of the crime.,"[Action, Science Fiction, Adventure]","[rescue, mission, dream, airplane, paris, ...","[Legendary Pictures, Syncopy, Warner Bros. P...","[English, French, Japanese, Swahili]",en,"Inception Cobb, a skilled thief who commits co..."
1,Interstellar,The adventures of a group of explorers who mak...,Mankind was born on Earth. It was never meant ...,"[Adventure, Drama, Science Fiction]","[rescue, future, spacecraft, race against t...","[Legendary Pictures, Syncopy, Lynda Obst Pro...",[English],en,Interstellar The adventures of a group of expl...
2,The Dark Knight,Batman raises the stakes in his war on crime. ...,Welcome to a world without rules.,"[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secret identity, cr...","[DC Comics, Legendary Pictures, Syncopy, Is...","[English, Mandarin]",en,The Dark Knight Batman raises the stakes in hi...
3,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the world of Pandora.,"[Action, Adventure, Fantasy, Science Fiction]","[future, society, culture clash, space trav...","[Dune Entertainment, Lightstorm Entertainment...","[English, Spanish]",en,"Avatar In the 22nd century, a paraplegic Marin..."
4,The Avengers,When an unexpected enemy emerges and threatens...,Some assembly required.,"[Science Fiction, Action, Adventure]","[new york city, superhero, shield, based on...",[Marvel Studios],"[English, Hindi, Russian]",en,The Avengers When an unexpected enemy emerges ...

#### Lowercasing all text in 'tags' column,to normalize it for text processing

In [40]:
moviess['tags'] = moviess['tags'].str.lower()

### Vectorization

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000 ,stop_words='english')
vectors = cv.fit_transform(moviess['tags'])

### Calculate similarity between movies

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(movie_title):
    # Get index of the movie
    idx = moviess[moviess['title'].str.lower() == movie_title.lower()].index

    if len(idx) == 0:
        print("Movie not found.")
        return

    idx = idx[0]

    # Compute cosine similarity between this movie and all others
    distances = cosine_similarity(vectors[idx], vectors)

    # Get top 5 similar movies (excluding itself)
    movie_list = sorted(list(enumerate(distances[0])), key=lambda x: x[1], reverse=True)[1:6]

    print("Top 5 similar movies to:", movie_title)
    for i in movie_list:
        print(moviess.iloc[i[0]].title)

In [45]:
recommend("The Dark Knight")

Top 5 similar movies to: The Dark Knight
Batman
Batman Begins
Batman: Mask of the Phantasm
The Dark Knight Rises
Criminal

# Let me expalin what is happening up there :)

This CountVectorizer fn converting words --> numbers,we create our CountVectorizer(cv) and applying using fit_transform(), we first learning 5000 words from tags column using max_features argument and aslo not learning some common words like (is,the,etc.) by stop_words argument.

now we have a Sparse Matrix, a matrix where most of the values are zero.
When we use CountVectorizer(max_features=5000)
  - it create a 5000-dimensional vector for each movie.
  - But each movie only uses maybe 20–50 words out of those 5000.
  - That means: the rest (~4950+) are all 0.
    - example:[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..., 2, ..., 0, ..., 1]


Instead of storing all those zeros, Python (and libraries like scikit-learn) use a smart format to only store:
  - The positions (coordinates) where the values are non-zero and their actual values
    - (0, 7)     1
      (0, 108)   2
      (0, 4000)  1


matrix Preview :
-         Word1  Word2  Word3  ... Word5000
          Movie1   1      0      2     ...   0
          Movie2   0      0      1     ...   3
          ...     ...    ...    ...    ...  ...

- Each row = a movie's tags
- Each column = a word from 5000-word vocabulary
- The cell = the number of times that word appears in the movie’s tags

In [72]:
cv = CountVectorizer(max_features=5000 ,stop_words='english')
cv.fit_transform(moviess['tags'])

CountVectorizer(max_features=5000, stop_words='english')

In [76]:
# First we finding the indexes in title column that match our given movie,we got three indexes as you can see
idx = moviess[moviess['title'].str.lower() == "Inception".lower()].index
idx

Index([0, 607631, 751545], dtype='int64')

In [59]:
# We only choosing only first movie index([0]) that's why 0 , and storing it in idx again convert the above output to pure int form
idx = idx[0]
idx

np.int64(0)

In [55]:
print(idx)

17

In [75]:
#For movie 0 ,The word at index 4481 in the vocabulary appeared 1 time
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 21969759 stored elements and shape (1226610, 5000)>
  Coords	Values
  (0, 4481)	1
  (0, 1090)	1
  (0, 3136)	1
  (0, 827)	1
  (0, 3660)	1
  (0, 3148)	1
  (0, 2651)	1
  (0, 4410)	1
  (0, 1054)	1
  (0, 2300)	1
  (0, 3295)	1
  (0, 2272)	1
  (0, 4409)	1
  (0, 2914)	1
  (0, 3883)	1
  (0, 1145)	1
  (0, 168)	1
  (0, 3890)	1
  (0, 1779)	1
  (0, 200)	1
  (0, 3698)	1
  (0, 2929)	1
  (0, 1440)	2
  (0, 237)	1
  (0, 3233)	1
  :	:
  (1226608, 1548)	1
  (1226608, 2851)	1
  (1226608, 4117)	1
  (1226608, 218)	1
  (1226608, 2666)	1
  (1226608, 3282)	1
  (1226608, 2704)	1
  (1226608, 3120)	1
  (1226608, 1615)	1
  (1226608, 840)	1
  (1226608, 3157)	1
  (1226608, 2656)	1
  (1226609, 4949)	1
  (1226609, 1548)	1
  (1226609, 2249)	2
  (1226609, 987)	1
  (1226609, 275)	2
  (1226609, 2515)	1
  (1226609, 2805)	2
  (1226609, 2517)	2
  (1226609, 153)	1
  (1226609, 808)	1
  (1226609, 3469)	2
  (1226609, 800)	1
  (1226609, 2099)	2

Here we caculating similarity
- Calculates cosine similarity between "given movie" and all movies
-  Cosine Similarity Formula:
   Cosine Similarity Formula:

$$ \text{similarity}(A, B) = \frac{A \cdot B}{||A|| \cdot ||B||} $$

Measures angle between two vectors.

Value between 0 and 1.

1 → exactly similar

0 → completely different

In [84]:
distances = cosine_similarity(vectors[idx], vectors)
print("shape of our 2D NumPy array:",distances.shape) #It's comparing 3 movie (the one at idx)
# Against 1,226,610 movies (the full dataset)
# We get 3 row, with 1226610 similarity scores.
print(distances[0]) # similarities for movie at index 0 with all others movies
print(distances[1]) # similarities for movie at index 607631 with all others movies
print(distances[2]) # similarities for movie at index 607631 with all others movies
# Each distances[i] is a 1D array of 1226610 similarity scores.

shape of our 2D NumPy array: (3, 1226610)
[1.         0.13280318 0.20211302 ... 0.02618914 0.14054567 0.04888237]
[0.17213259 0.03086067 0.03131121 ... 0.06085806 0.08164966 0.05679618]
[0.15097027 0.0541332  0.0549235  ... 0.05337605 0.14322297 0.04981355]

In [94]:
e =(enumerate(distances[0]))
print(e)

<enumerate object at 0x000002A2ECE444A0>

That’s because enumerate() returns a special object called an enumerator, not a list. It's an iterator, which means it doesn't hold the data directly — it's just a generator that can give the data when we loop over it.

It doesn't automatically show the content when we print it.To see the actual values we have to convert it to list.

In [95]:
e =list(enumerate(distances[0]))
print(e)  # too big

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [96]:
print(e[:5])

[(0, np.float64(0.999999999999999)), (1, np.float64(0.13280317881493264)), (2, np.float64(0.20211302086361085)), (3, np.float64(0.12326671027227311)), (4, np.float64(0.13608276348795434))]

Output is list of tuples.

In [101]:
 index , value = e[0]
 print((index, float(value)))

(0, 0.999999999999999)

movie’s index and its similarity score with the target movie.

- enumerate(distances[0]) → creates index-value pairs from distances[0]
- sorted(..., key=lambda x: x[1], reverse=True) → sorts these pairs by the similarity score (not index) in descending order.
 Note: x[1] refers to the second element of the tuple, which is the similarity score.
- [1:6] → takes the top 5 most similar items, excluding the first one (usually the item itself).

In [ ]:
movie_list = sorted(list(enumerate(distances[0])), key=lambda x: x[1], reverse=True)[1:6]

Looping through movie_list, which contains tuples like (index, similarity_score), and we are doing the following for each one:

- i[0] → the index of a similar movie.

- moviess.iloc[i[0]] → fetches the row at that index from the DataFrame moviess.

- .title → accesses the title column of that row.

In [ ]:
for i in movie_list:
        print(moviess.iloc[i[0]].title)

# **SAVE MODEL & VECTOR FOR REUSE**

In [102]:
import pickle

# Save your data
pickle.dump(moviess,open('movies.pkl','wb'))

# Save the CountVectorizer object
pickle.dump(cv,open('vectorizer.pkl','wb'))

# Save the vectorized matrix
pickle.dump(vectors,open('vectors.pkl','wb'))